### ISSUE TITLE
Design OAuth dialog

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#1]
Need a dialog to show users who use the webmaker OAuth service (e.g. from teach.mozilla.org).

This might not be necessary if we can properly white-list teach.mozilla.org (right, @jbuck ?).

**Comment by secretrobotron** [comment]
de-milestoning this because it's not necessary for teach implenentation
(cc @jbuck)

**Comment by cassiemc** [comment]
@secretrobotron is this necessary at all? can we close?

**Comment by secretrobotron** [comment]
:+1: let's close it. We're going to whitelist teach so this dialog won't pop up. If we need it, we can re-file.
