### ISSUE TITLE
Create user migration email

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#109]
- [x] Find a reference email
- [x] Create copy for it
- [x] File bugs to hook it up
- [ ] IMPLEMENT

**Comment by secretrobotron** [comment]
Reference email: https://github.com/mozilla/webmaker-mailroom/blob/master/locale/en_US/login_request.json

**Comment by secretrobotron** [comment]
Current login reset email looks like this:
![screenshot 2015-04-01 15 51 28](https://cloud.githubusercontent.com/assets/403231/6950182/0c315c0c-d887-11e4-9952-61e8f7735df0.png)

**Comment by secretrobotron** [comment]
From Kevin:
> Webmaker is using a new log in system to ensure your experience is simple and safe. To get started, click here to set a password, or copy and paste this migration token into the text field:  xxx

I'd leave the message at the bottom too:

> If you did not try to sign in, you can ignore this message, or send an email to help@webmaker.org to ask for help.

**Comment by secretrobotron** [comment]
@cadecairos can you list the patches you'll need to make for this (like you did on our call yesterday)?

**Comment by cadecairos** [comment]
1. Login.wmo - needs a way to indicate that sawmill should render a migration token email VS regular token login email
2. webmaker-mailroom - migration email template, strings
3. sawmill - check for flag on token login emails to trigger a switch to the migration email template.

**Comment by secretrobotron** [comment]
Subject line: "Set up your new Webmaker account password"

Remove the second button. Just make the first one say "Set Password".

**Comment by secretrobotron** [comment]
@KevZawacki looking at, "copy and paste this migration token into the text field," it might make more sense as "copy and paste this migration token into the text field on [link to set password page]this page[/link]".

**Comment by KevZawacki** [comment]
@secretrobotron +1, agreed

**Comment by cadecairos** [comment]
bloker bugs in login, sawmill and webmaker-mailroom are all landed, I'm working on wiring everything together.

**Comment by cadecairos** [comment]
fixed in #194
