### ISSUE TITLE
Document and/or implement logout API

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#119]
I'm noticing as I use the server that it automatically calls my OAuth2 callback (without prompting the user) if the user is already logged-in. This seems to imply that there should be some kind of logout endpoint that I can ping in order to explicitly log *out* of the id server--without such a feature, for instance, there seems to be no way for one user to log out of the teach website and then hand their device to another human, who can then log in as a different user. (This isn't just an edge case, it's also a security hazard, as there's effectively no way to log out of the system--upon clicking 'login', the second user would immediately be logged in as the first user without any prompting.)

In fact, it seems the only way I can forcibly "log out" of the system right now is to change the server's cookie secret, which invalidates my sesssion cookie! lol. So implementing and/or documenting a logout endpoint would be very helpful here.

**Comment by toolness** [comment]
Note that simply *documenting* this API will help unblock https://github.com/mozilla/teach-api/pull/11, so if it's faster for you to first document and implement later, that's cool too.

**Comment by toolness** [comment]
Er, wait a minute... I'm really confused now.

What is the user's mental model for webmaker login? Should logging into the Teach site log the user into all of webmaker? And should logging out of the Teach site log them out of all of webmaker?

Alternatively, is Teach login/logout state independent of "core webmaker" login state, the same way that, say, logging in/out of a Discourse instance with Google is largely independent of one's Google login state? (e.g., it's not the case that when one clicks "logout" in Discourse that they are also logged out of all of Google. I assume one can also login to Discourse as Google user A, then go to google.com and switch to Google user B, and when they go back to Discourse they'll still be recognized as Google user A.)

I guess this raises a lot of the same questions that Crystal Beasley's [How people *think* facebook connect log-in and log-out work](http://skinnywhitegirl.com/blog/how-people-think-facebook-connect-login-logout-work/861/) study analyzed.

**Comment by toolness** [comment]
Also, while using the "global webmaker login" mental model may ultimately be more user-friendly, at least for core webmaker properties, I have some concerns about the technical implementations, as it sounds less like OAuth2 and more like [Persona's Observer API](http://identity.mozilla.com/post/28513408358/a-new-api-for-persona).

**Comment by jbuck** [comment]
Right, so the idea is that if the user is already logged in and has already approved the client application to access their information then they should just be redirected back to the client application.

This does imply that there are two different login states, one for id.wm.o and one for the client application. As you said, we're aiming for an experience akin to Discourse w/ Google sign-in.

I think we do need to have some sort of user experience living on id.wm.o where you can sign-out, or have some way of applications to signal that they should be signed out of id.wm.o.

**Comment by toolness** [comment]
Hmm ok. Just as an FYI, when I talked to the designers on our Teach site stand today, they thought this behavior was a bit odd, since the Teach site is kind of like a "core" webmaker property (well, ok, it was *really* core back when it was actually on the webmaker.org domain and had the webmaker log on it, but still).

In other words, it makes sense for logging out of Discourse to not log you out of Google because those are understood by the user to be completely different properties, owned by completely different organizations and used for totally different things... But that's not necessarily the case with Teach vs. the rest of webmaker, is it?

Anyhow, all that said it also seems more technically [challenging](https://github.com/mozilla/id.webmaker.org/issues/119#issuecomment-88909530) to do it a different way, so given our time constraints I think your suggestion is the only option regardless.

> I think we do need to have some sort of user experience living on id.wm.o where you can sign-out, or have some way of applications to signal that they should be signed out of id.wm.o.

How should we do that? It seems like a blocker for launch, since we don't want it to be possible e.g. for me to log into the Teach site on a friend's computer and then log out, only to have the user click "login" and immediately be logged in as me, since I'm actually still logged into id.wm.o...

**Comment by toolness** [comment]
FWIW, I think a simple `/logout` endpoint that also takes a `next` querystring arg that immediately redirects the user to the given URL could be really useful, as it'd allow us to optionally have logout work a bit like the login flow--essentially killing the user's session for id.wm.o and then bouncing them back to the Teach site.

**Comment by thisandagain** [comment]
"I think a simple /logout endpoint that also takes a next querystring arg that immediately redirects the user to the given URL could be really useful"

:+1: Really great catch @toolness.

**Comment by secretrobotron** [comment]
That's the solution we talked about on Thursday in the daily. @cadecairos is on it.
