### ISSUE TITLE
Design QA review

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#12]

**Comment by secretrobotron** [comment]
@alicoding when #6 #7 #8 #2 #30 #32 are closed, and you give us the green light, let's do the design review using  http://loginv4.herokuapp.com/login with @cassiemc.

**Comment by alicoding** [comment]
CC @Pomax

**Comment by alicoding** [comment]
Not sure if we want to do the QA before the API or do that right away?

I guess we shouldn't be blocked on that part, but the UX would be a bit weird...

**Comment by cassiemc** [comment]
@alicoding @Pomax Let's do it asap. Can we get a link up that I can review?

**Comment by alicoding** [comment]
@cassiemc just waiting for @Pomax to review my PR then we should push this up with the latest changes.

**Comment by jbuck** [comment]
@cassiemc https://id.mofostaging.net/login

**Comment by cassiemc** [comment]
@alicoding @Pomax has the link been updated with most recent changes yet? Would love to look at signup before I leave today if possible.

**Comment by secretrobotron** [comment]
Did a final sweep with @vazquez (thanks). Filed a bunch more bugs. Will close them up.
