### ISSUE TITLE
Write test suite for back-end

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#14]
- [ ] docs for adding new tests
- [ ] coverage for major routes & API calls
- [ ] error/success state coverage
- [ ] travis integration (calls `npm test`)

**Comment by secretrobotron** [comment]
@Pomax perhaps we should do this before any real code gets written (#15), using TDD. Thoughts?

**Comment by Pomax** [comment]
actually moving this over to @cadecairos for the moment, since that works' already being done right now without me being involved in it

**Comment by jbuck** [comment]
Yeah, we've been doing this as we go
