### ISSUE TITLE
Signup page: enter button to submit form

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#147]
Pushing the "enter" button on the signup page form should submit the form.

**Comment by alicoding** [comment]
It is actually doing that by default now if we focus on the button (using tab key to the button) then press the "Enter" or "Space" key it should submit the form by default

**Comment by secretrobotron** [comment]
Is it? In the patch I just tried, pressing tab took me to a couple of links and a checkbox before I could submit the form. Shouldn't we just allow people to push enter and continue?

**Comment by alicoding** [comment]
You mean press enter while the fields still empty?

**Comment by secretrobotron** [comment]
e.g.
1. Click on username box, type something.
2. Tab to email box, type something. 
3. Tab to password box, type something.
4. Press enter.

What should happen? I would think the form would submit. @vazquez is that common practice?

**Comment by alicoding** [comment]
Hmm why it says I closed this?

**Comment by alicoding** [comment]
I will wait for @vazquez to confirm the UX here, but I agree with you on pressing enter part

**Comment by secretrobotron** [comment]
No worries. Moved to backlog. Doesn't need to block shipping this milestone.

**Comment by alicoding** [comment]
closing as dup of https://github.com/mozilla/id.webmaker.org/issues/196
