### ISSUE TITLE
Write test suite for front-end

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#16]
Once #6, #7, #8, and #15 are done, it would be great to have @k88hudson and @gvn help us build some automated front-end tests.

**Comment by k88hudson** [comment]
Sounds good @secretrobotron. What we do will depend on how this is implemented – for example, are you using React? etc.

I would prefer to hold off on doing too much fine-grained automated testing until the design +  implementation (particularly the UX flow) is a little farther along/more mature.

Some options here:
* Where possible, ask your engineers to write js that doesn't touch the DOM as separate modules so we can write unit tests with mocha
* If you're doing React, I recommend using the React test utils to test components as well as property validation (if you look at teach.webmaker.org, there are good examples there). Also possibly some smoke tests that check for accessibility errors and react errors on each page.
* If you're not doing React, @gvn's phantom tests (see https://github.com/mozilla/webmaker-profile-2/blob/master/test/phantom.js) might be a good option
* For cross-browser testing, I think saucelabs is a good option. I have a PR in progress here https://github.com/mozilla/teach.webmaker.org/pull/314

**Comment by secretrobotron** [comment]
Yeah, that's perfect. As soon as things start coming together, I'll tap you on the shoulder again.

cc'ing @alicoding since he's putting together the UI.

**Comment by k88hudson** [comment]
I'd also like to know how routing and components are going to work on the front end, as well as the directory structure. @jbuck @alicoding can you let me know when you make a decision on that (or if you already have)? Thanks :)

**Comment by secretrobotron** [comment]
@alicoding @Pomax we should do this on a per-component basis. Should include functional tests (success/fail states, check XHR responses, etc.). Broadly...

- [ ] success/error states for each component
- [ ] check routes to see that they exist and expected pages (sauce testing)

Anything else?

**Comment by k88hudson** [comment]
So far we've got test harness in place for browser tests, some commands (with npm test), two ways of viewing them (browser/mocha-phantomjs), and some tests for the first two components. 

Hopefully we can continue to write tests for new componetns
