### ISSUE TITLE
Valid user+email but invalid password sends email to user

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#175]
On `/signup`, using a valid username and email and an *invalid* password will not appear to succeed (i.e. return to teach site), but will send me an email.

In other words, an signup with an invalid password will send me an email but not properly create an account (or so it seems).

Found during QA in #11

**Comment by jbuck** [comment]
The issue here is that the login server creates the user account *then* verifies that the password meets strength requirements. I've flipped the order and now you don't have this orphaned account.

**Comment by jbuck** [comment]
This is deployed on staging now!
