### ISSUE TITLE
Nickname validation doesn't check for availability

### ISSUE THREAD

**Issue by thisandagain** [mozilla/id.webmaker.org#178]
The validator for nicknames should check for availability onBlur (or possibly even keyDown w/ a throttle). Currently, the field validates as "ok" with the green checkmark. Once the user clicks, "SIGN UP" the page hangs with no feedback presented to the user.

Example (this nickname is already taken):
![screen shot 2015-04-08 at 10 02 24 am](https://cloud.githubusercontent.com/assets/747641/7050474/697be78e-ddd6-11e4-9a55-1bf59a97d9f0.png)

**Comment by secretrobotron** [comment]
Should be covered by https://github.com/mozilla/id.webmaker.org/issues/176

**Comment by secretrobotron** [comment]
For #11 (QA)

**Comment by secretrobotron** [comment]
Should validate email uniqueness too until #193 is done.

**Comment by secretrobotron** [comment]
Done. Filed #222 for email.
