### ISSUE TITLE
Tab doesn't focus the next field on sign-up form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/id.webmaker.org#179]
I had to hit Tab twice in order to focus the field. The first Tab seemed to select the field.

Found during QA in #11

**Comment by secretrobotron** [comment]
Signup page
Trying to get from username -> email, or email -> password
Needed to hit tab twice every time.

**Comment by alicoding** [comment]
fixed by https://github.com/mozilla/id.webmaker.org/commit/d10b894d372d9de9f45dccfb46a315d90d7ff379
