### ISSUE TITLE
Build OAuth service

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#18]
Simplified/helpful modules to use:
- https://github.com/jaredhanson/oauth2orize#related-modules
- http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified

**Comment by cadecairos** [comment]
http://blog.papersapp.com/oauth-server-in-node-js/ might be a useful resource (if we go the express route)

**Comment by davidascher** [comment]
Didn't @toolness build a thing like this last year?

**Comment by secretrobotron** [comment]
I think he did, yeah! Not sure how much is reusable. @toolness ?

**Comment by cadecairos** [comment]
I think it's using OAuth 1.0 vs 2.0

**Comment by toolness** [comment]
Correct, it is using OAuth 1 instead of 2, alas:

https://github.com/toolness/webmaker-connect

Because it was made early last year, it uses Persona for login. Lots of tests though, yay!

**Comment by secretrobotron** [comment]
Yay, tests! Should make @Pomax happy here.

**Comment by Pomax** [comment]
Should make @̶P̶o̶m̶a̶x̶ everyone happy here.

**Comment by Pomax** [comment]
also, https://www.npmjs.com/package/oauth2-server ?

**Comment by alicoding** [comment]
@Pomax would that work with Hapi?

**Comment by Pomax** [comment]
that depends on whether Hapi was smart enough to allow the same type of modules to be loaded really. I've not used Hapi yet so I can't say.

**Comment by secretrobotron** [comment]
This looks about done now. Thanks for filling it out @cadecairos .
