### ISSUE TITLE
Password field needs better error message

### ISSUE THREAD

**Issue by hannahkane** [mozilla/id.webmaker.org#181]
Need to convey conditions for a successful password

**Comment by secretrobotron** [comment]
@cadecairos what are the conditions for a good password?
@alicoding Can we put some instructions within the warning box, or in the textbox itself?

**Comment by secretrobotron** [comment]
Should be good error reporting from #176 as well.

**Comment by secretrobotron** [comment]
@vazquez says:
* should be a popup really similar to the warning popup
* nothing static, because it'll be in the way

**Comment by alicoding** [comment]
blocked on this for signup page https://github.com/mozilla/id.webmaker.org/issues/205

**Comment by alicoding** [comment]
https://github.com/mozilla/id.webmaker.org/commit/6900a30f18021c8f5692731e24072f1c67a13ada
