### ISSUE TITLE
Link for "Tell me abut Mozilla news & events" not working

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/id.webmaker.org#182]
Testing login in Firefox - #11 

When I select that box, it takes me way down to the bottom of the login page. Just seeing the background image of the page (blue/triangles)

**Comment by ldecoursy** [comment]
Experienced the same on Firefox on Android

**Comment by alicoding** [comment]
This is fixed by https://github.com/mozilla/id.webmaker.org/commit/d10b894d372d9de9f45dccfb46a315d90d7ff379
