### ISSUE TITLE
Need copy on login page to connect teach.mozilla.org and webmaker

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/id.webmaker.org#183]
As a user, when I get to the login page, that's the first I'm seeing of the Mozilla Webmaker logo. Will need some copy to connect the dots, and ideally a link from that page to return to teach.mozilla.org if for any reason someone decides not to create an account. 

Found during #11

**Comment by secretrobotron** [comment]
Considering we know where the user came from because of the OAuth client ID, can we say, "You came here from xxxx website" or something?

cc @jbuck @cadecairos ?

**Comment by ldecoursy** [comment]
Or maybe something like "We use the same login system for teach.mozilla.org as we do for Mozilla Webmaker, so you'll be able to access both sites with the same account."  or "Creating an account for teach.mozilla.org will also give you access to Webmaker.org."

**Comment by secretrobotron** [comment]
@cassiemc could I get your opinion here? Should we add a small blurb to the login/signup pages and back button?

**Comment by cassiemc** [comment]
I think if we can detect that users came from teach or from a teach email, a user-specific blurb is smart. Otherwise I feel like the button design was meant to accomplish what Lainey is asking for here, by making the relationship explicit (I don't actually see the button I designed - which had the webmaker logo - implemented on https://teach.mofostaging.net/ – I can't find the issue but will dig it out after my next meeting. Maybe @hannahkane knows the status of that?

**Comment by cassiemc** [comment]
Here's the redpen (I believe we were going with I) https://redpen.io/vy733a8b80210605bd

**Comment by hannahkane** [comment]
I was looking for the ticket that had those designs yesterday, and I can't for the life of me find it, in this repo or the Teach repo, so I'm just going to create a new ticket in Teach to implement one of those button designs. Thanks, @cassiemc.

**Comment by secretrobotron** [comment]
:+1: If we make a change to the button, maybe we forego adding text to login right away. This ticket can move to backlog and we can focus on shipping. Sound smart @cassiemc @ldecoursy ?

**Comment by cassiemc** [comment]
wfm! And here's the issue @hannahkane : https://github.com/mozilla/id.webmaker.org/issues/2

**Comment by secretrobotron** [comment]
:+1: We need an implementation bug on the teach site now.

**Comment by secretrobotron** [comment]
https://github.com/mozilla/teach.webmaker.org/issues/700
