### ISSUE TITLE
The sign up page is extremely long

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/id.webmaker.org#185]
I just tried to sign up using the login flow from the new teach site. When I got to the sign up page, I noticed that the page scrolls down excessively - seen on desktop Firefox. 

![screen shot 2015-04-08 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/535012/7053581/5445099e-de04-11e4-8fef-a5a848976ff6.png)

![screen shot 2015-04-08 at 3 31 44 pm](https://cloud.githubusercontent.com/assets/535012/7053611/886d3d18-de04-11e4-88e8-8eba676620f9.png)

![screen shot 2015-04-08 at 3 31 55 pm](https://cloud.githubusercontent.com/assets/535012/7053614/8b9790ce-de04-11e4-9505-cbb24a363111.png)

![screen shot 2015-04-08 at 3 32 02 pm](https://cloud.githubusercontent.com/assets/535012/7053617/8e9a0f5e-de04-11e4-8acd-8126d6d20468.png)

**Comment by secretrobotron** [comment]
Suuuper weird.

**Comment by secretrobotron** [comment]
For #11 (QA)

**Comment by alicoding** [comment]
that's fixed by https://github.com/mozilla/id.webmaker.org/pull/184/files
