### ISSUE TITLE
MOBILE: Signup button not working on Android

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/id.webmaker.org#186]
I entered data in all three fields, but hitting "Sign Up" button and nothing is happening.

Found during #11 
Firefox on Android

**Comment by secretrobotron** [comment]
@ldecoursy this works fine for me, actually. Can you jot down some steps to how you got to this point?

**Comment by ldecoursy** [comment]
Clicked Login, then Signup, then entered username, email, password, click "Sign Up" button, nothing happens.

**Comment by secretrobotron** [comment]
Ahhh ok. My hunch is that this is the same bug as #176.
cc @alicoding

**Comment by alicoding** [comment]
blocked on this https://github.com/mozilla/id.webmaker.org/issues/205

**Comment by secretrobotron** [comment]
:+1: confirmed with @alicoding works!
