### ISSUE TITLE
Build user storage/retrieval service

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#19]
Includes
* DB interface
* Method for storing and retrieving new users
* Method for retrieving existing users

**Comment by secretrobotron** [comment]
cc @Pomax @jbuck

**Comment by cadecairos** [comment]
Brain Dump!

the id.wm.org user API needs to enable the following:

#### Webmaker user logs in (has password)
1. id.wm.o checks it's user database, finds no user
2. id.wm.o attempts to verify user through login.webamker.org API succeeds
3. id.wm.o migrates user into id.wm.o user DB
4. id.wm.org sets session cookie

#### Webmaker user logs in (no password)
1. id.wm.o checks it's user database, finds no user
2. id.wm.o attempts to verify user through login.wm.org API fails
3. id.wm.o checks if user exists on wm.org using login.wm.org API, finds user
4. redirects client user agent to reset password page
5. ??????
6. user logs in with new password

**Comment by secretrobotron** [comment]
> id.wm.o attempts to verify user through login.wm.org API fails

Why does it need to fail? Can't you do a simpler check?

> ??????
hahaha how about, "User is directed to migration page," and then, "user received password reset email, follows link, resets password"

**Comment by jbuck** [comment]
We decided to proxy all user data to login.wm.o for now

**Comment by secretrobotron** [comment]
My understanding is that this isn't done yet though. @cadecairos ?

**Comment by jbuck** [comment]
Sign-in already works on https://id.wm.org, so we've got it started

**Comment by cadecairos** [comment]
> My understanding is that this isn't done yet though.

it's a WIP
