### ISSUE TITLE
Pressing enter in login form doesn't submit it

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#196]
I'm not sure if this is a duplicate or not, but I've noticed that once I've entered my username and password in the login form, and when my input focus is still in the password field, pressing enter doesn't submit the form.

The "pressing enter submits the currently focused form" behavior seems like a UX convention that most sites adhere to, so others might be confused by the current behavior.

**Comment by toolness** [comment]
Hmm, upon inspection it seems the form isn't actually contained in a `<form>` element, and the submit button doesn't have a `type="submit"` on it. Doing these simple things, and adding an `onSubmit` handler to the form that calls `event.preventDefault()`, and instead does whatever currently happens when the button is clicked, should do the trick.

**Comment by secretrobotron** [comment]
For #11 (QA).

**Comment by secretrobotron** [comment]
Fixed via #242.
