### ISSUE TITLE
Firefox password manager doesn't work with login form

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#197]
I've noticed that Firefox doesn't ask me if I want it to remember my username/password when I submit the login form, which is a bummer. Haven't tried it on other browsers though.

**Comment by toolness** [comment]
As mentioned in https://github.com/mozilla/id.webmaker.org/issues/196#issuecomment-91370755, I'm guessing the fact that the login form isn't actually in a `<form>` is probably the culprit for this. Should hopefully be a simple fix that relieves a lot of potential frustration!

**Comment by secretrobotron** [comment]
For #11 (QA).

Anything we can do about this, @alicoding ?
