### ISSUE TITLE
Design Login button to show on non-webmaker sites

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#2]
Need a recognizable login button to show on non-webmaker sites (e.g. teach.mozilla.org) which will launch the webmaker OAuth process.

**Comment by cassiemc** [comment]
Lotsa options here: https://redpen.io/vy733a8b80210605bd
@iamjessklein is design reviewing

**Comment by cassiemc** [comment]
@iamjessklein likes D & G
I like D, G and I.
Thoughts @secretrobotron @alicoding @vazquez ?

**Comment by cassiemc** [comment]
Ah, I should've pinged @hannahkane here too (sorry Hanhah).
Top three options are here, feel free to comment on redpen: https://redpen.io/vy733a8b80210605bd
![teach-login-buttons-options-v2](https://cloud.githubusercontent.com/assets/1186326/6838187/bc36b0ae-d32b-11e4-8304-f4df58326fe3.jpg)

**Comment by vazquez** [comment]
I like I the best. I think it's the one that works best based on the shifting colours of the navigation.

**Comment by cassiemc** [comment]
Great thanks @vazquez. Let's go with this version if it works for you @hannahkane? The 1-color webmaker logomark svg is here: https://www.dropbox.com/s/4yndkmm0b1b92u3/logo-webmaker-flat.svg?dl=0

![teach-login-button](https://cloud.githubusercontent.com/assets/1186326/6847975/ceb4101c-d3a0-11e4-86b4-d72c1664be78.png)

Will wait for hannah's :+1: before closing this.

**Comment by iamjessklein** [comment]
sounds good to me - it works nicely with our design. :+1:

**Comment by hannahkane** [comment]
wfm. Thanks, @cassiemc!
