### ISSUE TITLE
Conduct security review

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#20]
Need to make sure there is less code, more tests, and tests specific to security issues.

**Comment by secretrobotron** [comment]
cc @Pomax @jbuck @cadecairos

**Comment by k88hudson** [comment]
Just to let you know we have a opsec review ticket open on bugzilla that I need to update at some point related to the mobile implementation of login/integration with Firebase https://bugzilla.mozilla.org/show_bug.cgi?id=1138595&GoAheadAndLogIn=1

**Comment by thisandagain** [comment]
Blocked by #5

**Comment by simonwex** [comment]
A couple things to add rate limiting to:

* [ ] username lookup
* [ ] password attempts
* [ ] forgot password emails

**Comment by adamlofting** [comment]
Because it's closely related, can this ticket also include:

- [ ] Crosscheck id.w.o against our [MoFo Data Practices](https://mana.mozilla.org/wiki/display/DATAPRACTICES/Foundation+Data+Practices)

**Comment by simonwex** [comment]
@jbuck and I will be going through the review process next week. I've scheduled some time with him on Tuesday.
We'll be following this:
https://wiki.mozilla.org/Security/ReviewProcess#General_Web_Application_Review_Process
And ensuring this is followed: 
https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines

**Comment by secretrobotron** [comment]
@simonwex @jbuck trying to have things in shape to QA on Wednesday. Think we can do the security review on Wednesday/Thursday as well?

**Comment by simonwex** [comment]
@secretrobotron we're starting this *right now*. @jbuck or myself will leave an update here. We don't typically do these, so there's a bit of risk here.

**Comment by secretrobotron** [comment]
Need to deal with CSRF: https://github.com/mozilla/id.webmaker.org/issues/213
