### ISSUE TITLE
Email validation doesn't check for uniqueness

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#222]
Following from #178, `/signup` should also check to see if the email you use is unique (because of current loginapi server restriction).

**Comment by secretrobotron** [comment]
Might be taken care of in #176. @alicoding ?

**Comment by alicoding** [comment]
@secretrobotron it doesn't seem like we handle this server side at all or is just not implemented...

**Comment by secretrobotron** [comment]
@cadecairos ^^ ? We should try to do something here, imo. I don't think it's a hard blocker, because the LoginAPI will deny you anyway, but we should do the same kind of check that we do for username so that user experience isn't annoying.
