### ISSUE TITLE
Able to signup without password

### ISSUE THREAD

**Issue by alicoding** [mozilla/id.webmaker.org#223]
STR:

* Go to `/signup`
* Pick any username thatYouThinkNoOneEverRegisteredBefore
* Choose email address that was registered before
* Enter weak password like `alialiali`
* You will get error 400 but ignore that and change your email to one that you dontthink@someonetookitbefore.com
* Hit submit

Actual:
That account was created silently
Expected:
It should not allow that and give an error

**Comment by alicoding** [comment]
@secretrobotron @cadecairos ^^

**Comment by secretrobotron** [comment]
@alicoding #227 merged. Can this close?
