### ISSUE TITLE
Typo on Clubs page on teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/id.webmaker.org#231]
In the first item on the list on the clubs page, "literacy" is spelled incorrectly (currently spelled as literary) https://teach.mofostaging.net/mozilla-web-clubs/

![screen shot 2015-04-16 at 2 29 03 pm](https://cloud.githubusercontent.com/assets/4885898/7188350/181f76b0-e445-11e4-901f-f10401ce2b47.png)

**Comment by hannahkane** [comment]
@secretrobotron  can you close this here, please? I'll file it on the teach repo. Sorry for the miscommunication, @ldecoursy !
