### ISSUE TITLE
UI designs/UX flows

### ISSUE THREAD

**Issue by k88hudson** [mozilla/id.webmaker.org#25]
Hey, I was just wondering where the latest UI designs/UX flows are?

**Comment by k88hudson** [comment]
cc @secretrobotron @cassiemc

**Comment by k88hudson** [comment]
Also sorry, I am a total inVision n00b :P

**Comment by secretrobotron** [comment]
We're relying on a flow that @thisandagain [designed](https://github.com/mozilla/webmaker.org/issues/1364#issuecomment-77422354) a flow diagram that @jbuck has on his desk (specifically for first iteration implementation with teach site), and [UI designs](https://github.com/mozilla/webmaker.org/issues/1366) from @cassiemc .

Can we help you do something in particular? Are you investigating something?

**Comment by k88hudson** [comment]
mostly I was just wondering where they were so i could follow along. thanks for the ticket links, that works!

**Comment by secretrobotron** [comment]
AND https://projects.invisionapp.com/share/N52EKLSB2#/screens/67780360?maintainScrollPosition=false
