### ISSUE TITLE
Background image on login page

### ISSUE THREAD

**Issue by alicoding** [mozilla/id.webmaker.org#261]
There shouldn't be any background image on /login but when you visit /signup then switch to /login you will see background image.

**Comment by secretrobotron** [comment]
@alicoding I don't actually see this problem. How do you reproduce?

**Comment by alicoding** [comment]
STR:

1. https://id.mofostaging.net/signup
2. Click on "Login"

**Comment by secretrobotron** [comment]
Weird... mine looks fine. FF & Chrome. Just a grey page.

**Comment by alicoding** [comment]
I see this @secretrobotron 

![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/xu5w2vr8.png)

**Comment by secretrobotron** [comment]
So... so strange.
Can you try in private browsing?

**Comment by alicoding** [comment]
Yeah doesn't seem to trigger that on private mode... I'm closing this.
