### ISSUE TITLE
Users can't migrate with usernames with non-alpha-numeric characters

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#262]
![screenshot 2015-04-20 13 51 00](https://cloud.githubusercontent.com/assets/403231/7236685/574efb72-e764-11e4-8b68-332ccad2ffa9.png)

@alicoding @cadecairos @thisandagain might be a problem with only accepting alpha-numeric characters. At the very least, people can't migrate. What should they do?

**Comment by alicoding** [comment]
@secretrobotron I guess I just need the rule for this regex if we want to allow `-`, `_`, or any special characters that we might have for our previous signup validation?

**Comment by cadecairos** [comment]
check the regex used on login.webmaker.org

**Comment by secretrobotron** [comment]
:+1: let's do it
