### ISSUE TITLE
migrate flow from teach ended up at webmaker.org

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#263]
* Go to teach
* Click Login
* Use migration flow (for account with no password)
* Go to link in email
* Will wind up at webmaker.org after resetting password

**Comment by cadecairos** [comment]
I feel like we're missing a env param somewhere

**Comment by cadecairos** [comment]
haha nope. The href on the continue link is totally wrong

**Comment by secretrobotron** [comment]
wooo! Easy to patch though, right?

**Comment by cadecairos** [comment]
yup, testing a fix now
