### ISSUE TITLE
The same message should be returned to the user regardless of whether the username is valid or not

### ISSUE THREAD

**Issue by simonwex** [mozilla/id.webmaker.org#273]
![image](https://cloud.githubusercontent.com/assets/25260/7244895/42525d4e-e797-11e4-8977-183cc0a60799.png)

We do not want to provide any information that would allow an attacker to determine if an entered username/email address is valid or invalid. Otherwise an attacker could enumerate valid accounts for phishing attacks or brute force attack.

**Comment by jbuck** [comment]
Because user accounts are public information and the user experience suffers, I think we shouldn't implement the change you're suggesting.

**Comment by simonwex** [comment]
Good call, @jbuck.
