### ISSUE TITLE
Change link in Teach welcome email

### ISSUE THREAD

**Issue by hannahkane** [mozilla/id.webmaker.org#274]
As discussed in #4, we've now changed the path to the Clubs page, so we need to change the link in the Teach welcome email to teach.mozilla.org/clubs

(from https://github.com/mozilla/teach.webmaker.org/issues/750#issuecomment-94884142)

**Comment by secretrobotron** [comment]
@cadecairos can you just make sure sawmill is up to date on staging/prod?

**Comment by secretrobotron** [comment]
Needs to be https://teach.mozilla.org/clubs/ not https://teach.mozilla.org/clubs (notice the trailing slash).

@toolness should that be fixed on teach? Redirect from `clubs` to `clubs/`?

**Comment by toolness** [comment]
i suspect it is not redirecting because of https://github.com/mozilla/teach.webmaker.org/issues/785 as that redirect does work on staging.

**Comment by jbuck** [comment]
This redirect is working now, I think

**Comment by secretrobotron** [comment]
Fixed :D.
