### ISSUE TITLE
Design login user migration screen for desktop

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#28]
Finish design and present mocks/assets to @alicoding.

**Comment by cassiemc** [comment]
@secretrobotron To confirm, this is just the 'sign in' screen without a password field + a notification to set a password, yes? Am looking at the second row of this omnigraffle: https://drive.google.com/a/mozilla.com/file/d/0B-1AZgKn5Nc7OG9EUm5ieGZSZlU/view?usp=sharing

**Comment by cassiemc** [comment]
So, worth noting – I don't seen an IA for this on mobile, is that intentional? @thisandagain

**Comment by secretrobotron** [comment]
@cassiemc that's right.
And in the absence of something specific for mobile, we can make the page responsive. However, my guess is that it will be very similar to the other pages for mobile as well (just as most of the desktop pages are very similar).

**Comment by thisandagain** [comment]
Weird. Looks like a file is out of sync. I'll get that fixed for you. Either way, we are punting mobile for this heartbeat so not a blocker.

**Comment by cassiemc** [comment]
Some updated copy from @edrushka in https://github.com/mozilla/webmaker.org/issues/1366
>
Definitely agree there should be consistency in terms. I prefer 'key'. Suggest something along the lines of:
Title: Retrieve your key
Subtitle: We've emailed your key to the address you provided.
Hint text: Paste your key here
Button text: Submit Key to Log In

I noticed there is no confirmation screen in the ux flow. I think we should have a brief one though, then autodirect users to webmaker.org logged in state. That cool with you @thisandagain?

**Comment by thisandagain** [comment]
@cassiemc "Confirmation" as in loading or interstitial state after pressing "Log In"?

**Comment by cassiemc** [comment]
Here's what we have so far. There is some inconsistency with button language that I'd like to sort out – ie. login vs. continue – and would like to know if I should pursue the success screen. (On the success screen, I could have a 'continue' button instead of the 'now taking you to webmaker.org' message.

cc @secretrobotron 

![01-enter-username](https://cloud.githubusercontent.com/assets/1186326/6807577/ace2416a-d225-11e4-8ed2-9fd950147f82.jpg)
![02-enter-token](https://cloud.githubusercontent.com/assets/1186326/6807579/ace433a8-d225-11e4-8445-9d70d2dd32a5.jpg)
![03-set-password](https://cloud.githubusercontent.com/assets/1186326/6807580/ace63cc0-d225-11e4-9cc9-b45482a1282f.jpg)
![04-success](https://cloud.githubusercontent.com/assets/1186326/6807578/ace2da8a-d225-11e4-9acc-a43eeabc5099.jpg)

**Comment by cassiemc** [comment]
Also wonder if this would benefit from some kind of 1-2-3 status bar.

**Comment by cassiemc** [comment]
Also, question for @thisandagain re. the UX – How does the system know that you don't have a password associated with your account when you land on this page, or are you suggesting that the password field only appears after a user puts in their username?

**Comment by cassiemc** [comment]
@thisandagain just saw your comment -- yes, an interstitial state once you've set your password. You can see in the mocks above now.

**Comment by thisandagain** [comment]
@cassiemc Got it! Interesting ... I like it. I strongly recommend adding a button as doing solely a time-based redirect is going to be frustrating for many users.

**Comment by cassiemc** [comment]
Great! Here are success message design options. I'm leaning toward the second one.

![success-options](https://cloud.githubusercontent.com/assets/1186326/6810622/72e5f0d4-d238-11e4-9cb0-f700cc33e952.jpg)

**Comment by thisandagain** [comment]
I'm leaning towards option 3 as I feel like the first two are a little subtle.

**Comment by cassiemc** [comment]
I like the subtlety if we can also auto forward to webmaker.org after 3 seconds or something.

**Comment by cassiemc** [comment]
@vazquez can you weigh in here with design-review? Need to choose one of the three success messages (or iterate further)

**Comment by secretrobotron** [comment]
> I like the subtlety if we can also auto forward to webmaker.org after 3 seconds or something.

Me too. Let's just make sure @alicoding sees that for implementation.

**Comment by vazquez** [comment]
I think Option 2 works really well :)  
![screenshot 2015-03-24 22 28 48](https://cloud.githubusercontent.com/assets/1119821/6817288/279111c6-d275-11e4-8c62-0dd139780f94.png)

Only feedback, maybe increase the font weight one step on the "Continue" link? Not sure though, maybe the underline is enough.

**Comment by edrushka** [comment]
Gosh, option 2 is very subtle. If I saw that, I would try to click the check mark.

**Comment by cassiemc** [comment]
+1 on increasing font weight. I'm okay with subtle; to be clear, we want an auto-redirect after 3 seconds or so. There is no *need* to hit continue, it's just a option to speed through the process. Here's the updated success message screen:

![04-success-v2](https://cloud.githubusercontent.com/assets/1186326/6829547/777f7978-d2ea-11e4-887e-9efa39398680.jpg)

**Comment by alicoding** [comment]
I'm leaning toward option 2 if we are doing an autoredirect here since it is nice and clean :+1:

**Comment by cassiemc** [comment]
Ok, here are the final screens, which can be downloaded here: https://www.dropbox.com/sh/pimis2focff985a/AAB6tPz-RPApZjsDdMPplTQja?dl=0
* Note – I've removed the question marks from the password fields. I don't think we need them in this flow (you are setting a password for the first time in this flow, so there's no need to *reset* your password)

Let's file any additional design work on this as new issues. Thanks!

![01-enter-username](https://cloud.githubusercontent.com/assets/1186326/6829903/d73d2c78-d2ec-11e4-8e7e-01f6c60d77d5.jpg)
![02-enter-token](https://cloud.githubusercontent.com/assets/1186326/6829904/d73f3e96-d2ec-11e4-9521-2cf3f6815e72.jpg)
![03-set-password](https://cloud.githubusercontent.com/assets/1186326/6829905/d7415a78-d2ec-11e4-85b3-770aed1cd902.jpg)
![04-success-v2](https://cloud.githubusercontent.com/assets/1186326/6829906/d74173e6-d2ec-11e4-9e02-a6ad462cdcf0.jpg)
