### ISSUE TITLE
Can't sign up on id.webmaker.org (production) on Firefox or Chrome

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#280]
At https://id.webmaker.org/signup (and many other pages) on Firefox, nothing happens when I submit forms, with the error `TypeError: e is undefined` from `app.bundle.js:37:1494` logged to the console. The same error is often logged as I'm typing in form fields too.

The same page on Chrome doesn't seem to log that error, but it does show that `POST` requests to `/check-username` and `/create-user` are returning 403 (Forbidden).

**Comment by alicoding** [comment]
Apparently when I checked the request header CSRF Token is undefined...

**Comment by jbuck** [comment]
I didn't configure the CDN correctly to forward cookies... whoops

**Comment by jbuck** [comment]
Okay, updating the CDN now.

**Comment by jbuck** [comment]
Fixed!

**Comment by mijbr** [comment]
Dec  2019, I think I have a same problem. Can not signup. From android tablet.

**Comment by mijbr** [comment]
same from computer can't sign up

**Comment by ryanwarsaw** [comment]
@mijbr This software is deprecated and currently being phased out by Mozilla in production. The last major service that uses this is set to be phased out on December 16th, 2019 (Thimble). I believe signups were intentionally disabled as apart of this initiative.
