### ISSUE TITLE
Make Webmaker logo transparent white

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#285]
![login-logo](https://cloud.githubusercontent.com/assets/1186326/7401877/7a15cf40-ee95-11e4-8550-691c014234af.png)
Not sure what's going on but I see a black m on top of the webmaker logo. Looks like there is a red outline underneath, so maybe the m & shadow are overlapping something?

Anyway, here is the svg file again (it's all white): https://www.dropbox.com/s/vrrzml83bzf41lc/logo-webmaker-one-colour.svg?dl=0 

cc @secretrobotron not a blocker but we should fix if we can.

**Comment by secretrobotron** [comment]
Yeah, very strange. It's red in Chrome, black in FF.
