### ISSUE TITLE
Create metrics checklist from @adamlofting's template

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#3]
https://github.com/mozilla/mofo-metrics/wiki/Metrics-Checklists#metrics-requirements-checklist-project-kick-off

- [x] Create checklist
- [x] Go through it

**Comment by adamlofting** [comment]
I created the checklist and filled in the answers where I can guess so far.
https://github.com/mozilla/id.webmaker.org/issues/56
