### ISSUE TITLE
Design password reset screen for desktop

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#30]

**Comment by cassiemc** [comment]
How's this flow @secretrobotron @alicoding @Pomax @thisandagain? (including the omnigraffle screen shot for the email since that's not designed yet)

![01-username](https://cloud.githubusercontent.com/assets/1186326/6813828/4210376e-d24f-11e4-88aa-26db9ba17127.jpg)
![02-notifcation](https://cloud.githubusercontent.com/assets/1186326/6813831/421311c8-d24f-11e4-95df-4195854b270b.jpg)
![03-reset-email](https://cloud.githubusercontent.com/assets/1186326/6813829/4211bbac-d24f-11e4-91fd-41b83b0e5103.jpg)
![04-new-password](https://cloud.githubusercontent.com/assets/1186326/6813830/42128eb0-d24f-11e4-8e27-d3117af6425c.jpg)

**Comment by alicoding** [comment]
Do you think we should have confirm password field?

**Comment by secretrobotron** [comment]
* :+1: to confirm field -- with a client-side check to make sure both boxes have the same password, if possible
* button should probably say "Reset" unless they'll be logged in right away after filling in this form
* @cassiemc :+1: nice. first screen should have a small explanation, perhaps? e.g. "type your username, and we'll send you an email to reset your password"
  * or maybe it's already obvious?

**Comment by alicoding** [comment]
> first screen should have a small explanation, perhaps? e.g. "type your username, and we'll send you an email to reset your password"
or maybe it's already obvious?

I guess this will be obvious once they press the reset button and will see the instruction/message about email being sent to them? I think it's nice and clean :P

**Comment by cassiemc** [comment]
+1 to first button as 'reset'
+1 to second button as 'save'
I don't think we need the explanation upfront though, can keep it clean.

**Comment by cassiemc** [comment]
Here are two flows. One on the left is super simple as designed in the UX; the second one just has a message at the top that is more hand-holdy (not a bad thing for a user's state of mind at this juncture).

I am leaning toward B. Thoughts @secretrobotron @alicoding ?

![side-by-side-flows](https://cloud.githubusercontent.com/assets/1186326/6831724/8b232660-d2f8-11e4-83d5-b189785af5bc.jpg)

**Comment by alicoding** [comment]
I like option B. Option A is clean, but users might want some information as to what to expect before typing their username plus the design in option B doesn't really add much to that anyway, so :+1:

**Comment by alicoding** [comment]
Hmm thinking about it again the message might not be necessary in this case because the user clicked on the icon/link on the login page to get here, so they forgot their password which is obvious in this case and we are telling them what we're doing next on the next step anyway, so I think option A is better IMO.

**Comment by cassiemc** [comment]
@alicoding and I chatted about it in IRC and decided we are going to go with the simpler option A, see how users fare, then add in more description if they are getting lost. Let's file any additional changes as new bugs.

So to recap, here are the final screens, which can be downloaded here: https://www.dropbox.com/sh/ttu7vkoq9irawp1/AABg9lTGDBkSYzj_hdW7RZ3Aa?dl=0

![01-username](https://cloud.githubusercontent.com/assets/1186326/6835907/2ceeb05c-d314-11e4-9451-e59db6be7520.jpg)
![02-notifcation](https://cloud.githubusercontent.com/assets/1186326/6835908/2cf7de02-d314-11e4-9d1a-24ea83b0ec03.jpg)
![03-reset-email](https://cloud.githubusercontent.com/assets/1186326/6835910/2d076a70-d314-11e4-88a7-f205c4356916.jpg)
![04-new-password](https://cloud.githubusercontent.com/assets/1186326/6835909/2d029ef0-d314-11e4-8a2d-1bb44416af34.jpg)

**Comment by alicoding** [comment]
The UI for this one is completed only API left to be plug in.
