### ISSUE TITLE
Login isn't working on id.mofostaging.net

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#300]
When logging in via the website directly, after entering my username and password, I get a plaintext page at https://id.mofostaging.net/login/oauth/authorize with this content:

```json
{"statusCode":400,"error":"Bad Request","message":"invalid client_id"}
```

Also, when trying to login through http://teach.mofostaging.net, I get this page on teach-api.herokuapp.com:

> <h1>Login Error</h1>
> <p>Please <a href="https://teach.mofostaging.net/">go back</a> and try again.</p>
> <p><small><code>Error code: invalid_code_or_idapi_err</code></small></p>

Inspecting the server log shows this message:

```
POST /login/oauth/access_token returned 500 w/ content '{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}'
```

So it looks like id.mofostaging.net is returning a 500 at the `/login/oauth/access_token` endpoint.

**Comment by cadecairos** [comment]
I was able to successfully log in just now, this might have been a temporary hiccup somewhere.

I couldn't locate any suspicious logs.

**Comment by cadecairos** [comment]
(that was on prod)

Staging does indeed appear to be broken

**Comment by cadecairos** [comment]
Tracked it down to an out of date config on the staging server, caused by the addition of the password grant type:

https://github.com/mozilla/id.webmaker.org/commit/2d9fda15542ce40ed61564bed85865538b917c2a

I've made the required changes.

**Comment by cadecairos** [comment]
Going to call this resolved
