### ISSUE TITLE
Evaluate password strength requirements 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/id.webmaker.org#318]
It took me 15 minutes to set a password with enough entropy to satisfy Webmaker. It seems like 14 characters with a mix of uppercase, lowercase, numbers and a weird symbol or two should be enough for the accounts we are trying to protect. I knew what was happening but still wondered if the validation was broken. 

Can we dial this back a little bit? I worry that we will lose potential users on Android. 

cc @secretrobotron @simonwex

**Comment by thisandagain** [comment]
I'm seeing this as a regular frustration with users as well. I suggest we add promote this to launch blocker. Propose replacing rules with:

- Minimum password length: 6 characters
- Maximum password length: 256 characters

Remove all other constraints. If we want to protect users we should do it through throttling API requests and monitoring not by throwing up UX hurdles to the point where users end up writing passwords down on sticky notes. For those interested, there is a password management user research brown bag on Thursday that will address some of this. /cc @simonwex

**Comment by simonwex** [comment]
Totally agree with @thisandagain. The only thing that a more complicated password system does is make people write them down on post-its for others to see.

**Comment by ashleygwilliams** [comment]
:+1: i also agree.

the best thing i've found is making the suggestion that pass*phrases* are very safe. sentences are easier to remember than garbage characters and numbers, capital or not- they are also *way* safer. people don't even consider it an option unless you mention it.

https://xkcd.com/936/
![screenshot 2015-06-09 at 8 05 49 pm](https://cloud.githubusercontent.com/assets/1163554/8072367/f49b1d20-0ee2-11e5-8934-807bc26fb053.png)

**Comment by cadecairos** [comment]
> Minimum password length: 6 characters

I disagree, minimum should be 8, and even then that is considered weak (https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Password_Length)

If we're to remove other limitations we need at least two patches:

1. login.webmaker.org, to remove serverside strength checks
2. id.webmaker.org to remove server and client side strength

We can go even further and update webmaker-login-ux and any apps using it for login.

We should actively be encouraging passphrases if we're not enforcing other rules. I would also prefer if we continued disallowing the 10k most commonly used passwords

**Comment by xmatthewx** [comment]
If someone uses a common password, let's tell them and teach them (if we aren't already). Error : "That is a very common password and easy to guess. Try something else."

**Comment by cadecairos** [comment]
I had a chat with Cory Shields in IT about Mozilla's LDAP passphrase setup. They use a library called [passwdqc](http://www.openwall.com/passwdqc/), which just so happens to have been [ported to node](https://www.npmjs.com/package/passwdqc). it provides strength checks for all types of passwords: 1 character class (i.e. only lower case) up to 4 character classes, as well as passphrases.

It sounds like I should add that as a dependency in https://github.com/cadecairos/passtest and use it for all but the 10k common password check.

**Comment by ashleygwilliams** [comment]
:+1: i really like the passphrase setup for Mozilla's LDAP. :100: :heart:

**Comment by cadecairos** [comment]
Alright, I've got the solution for this, and it's [owasp-password-strength-test](https://www.npmjs.com/package/owasp-password-strength-test) and [PassTest](https://github.com/cadecairos/passtest).

I've updated passtest to use owasp-password-strength-test internally, and extend a test onto the utility to blacklist the 10k most common passwords.

I'm going to suggest the following configuration:
* Minimum length of 8
* Maximum length of 256
* must pass at least 2 optional tests (at least two character classes)
* must not be on common password list
* cannot repeat characters 3 or more times
* If length > 20 consider it a passphrase and don't worry if it would fail any optional tests.

**Comment by thisandagain** [comment]
Alright ... my final proposal:
- Minimum length of 8
- Maximum length of 256
- Must not be on common password list

**Comment by cadecairos** [comment]
https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Password_Complexity

Final offer, lol

**Comment by thisandagain** [comment]
:boom: LOL. :+1:

**Comment by cadecairos** [comment]
with the secure coding guidelines basically giving us a minimum set of requirements, lets say that passwords must have two types of characters minumum, rather than letters and numbers. i.e. lower case and capital or lower case and special chars

**Comment by cadecairos** [comment]
I've got PR's here:
https://github.com/mozilla/login.webmaker.org/pull/348
https://github.com/mozilla/id.webmaker.org/pull/319

I'm lost on how to get webpack to load a bloody js file though

**Comment by xmatthewx** [comment]
Resolved. Correct? By #348 and #319

**Comment by matthewsot** [comment]
Sorry if I'm misunderstanding the accepted fix to this, but https://id.webmaker.org/signup and https://id.mofostaging.net both still seem to require capital letters, even when using a number of different symbols, lowercase letters, a total password length of over 8 characters (which, to my understanding, should work according to @cadecairos' link). Can anyone else confirm this is happening, or is this how it's supposed to work?

I help run a web development club at my school where we're really excited to try Thimble (great work on that, it's awesome!), and would honestly rather run the risk of someone's account getting hacked than have to deal with people resetting their passwords every single time we meet because they can't remember it (or seeing them pull out a piece of paper with their password on it for everyone around them to see). These problems get magnified when using school computers which clear all stored browser passwords upon log out and which don't provide the option of using any other password manager.

Thanks!

**Comment by xmatthewx** [comment]
Thanks @matthewsot for the input. @k88hudson proposed a new solution to evaluate strength rather than a require a specific combination: https://github.com/mozilla/api.webmaker.org/issues/178
