### ISSUE TITLE
Cannot login through client app

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/id.webmaker.org#330]
I had a persona account that I wanted to switch over to Webmaker login. So, I logged into Persona and made the switch (after a few issues with the password).

Now, when I go to `id.webmaker.org/login` and enter my username, it shows that I am an existing user like so:
![screen shot 2015-06-24 at 3 34 50 pm](https://cloud.githubusercontent.com/assets/5816130/8339648/080075b8-1a87-11e5-8181-d214a2ff7ffa.png)

But then when I go to `bramble.mofostaging.net`, click on Login and try to enter my username, this is what I see:
![screen shot 2015-06-24 at 3 35 30 pm](https://cloud.githubusercontent.com/assets/5816130/8339666/203370a4-1a87-11e5-8e10-f9e8803639af.png)

Not sure, why that is happening. This is kinda blocking me from testing Thimble on staging.

cc @cadecairos, @jbuck, @simonwex

**Comment by gideonthomas** [comment]
Actually, now that I notice, it seems to be id on staging vs. `id.webmaker.org`
Should I be signing up for id on staging so that this works?

**Comment by cadecairos** [comment]
bramble.mofostaging.net uses id.mofostaging.net

**Comment by gideonthomas** [comment]
Thanks @cadecairos!

I just tried to do the exact same thing on `login.mofostaging.net` i.e. switch to use a password and I can login through `login.mofostaging.net` now. But I still seem to get the same thing on `bramble.mofostaging.net`

Any ideas?

**Comment by cadecairos** [comment]
what's the problem on bramble exactly?

**Comment by gideonthomas** [comment]
when I click on Login, it takes me to `id.mofostaging.net` to login. When I enter my username, I get the "We can't find an account with that username" message. But, when I go to https://login.mofostaging.net/account I see my account details, and it says "You have set a custom password"...is that not right?

**Comment by cadecairos** [comment]
I can log in, but when I do, bramble returns a 500 error until I remove my cookies. :/

**Comment by gideonthomas** [comment]
`bramble.mofostaging.net`? Yeah....it's sorta broken now

**Comment by gideonthomas** [comment]
@cadecairos so bramble is up and running again, and I have the same issue...maybe I'm in some weird bad transition state from persona to id.wm.org. Should I just create a new account and delete the old one instead?

**Comment by cadecairos** [comment]
I don't have access to the DB on staging so I can't confirm. you can either delete your account, or wait for @jbuck to take a look.

**Comment by gideonthomas** [comment]
awesome! I think for now I'll just delete my account! Thanks for your help @cadecairos

**Comment by xmatthewx** [comment]
Can we close this as resolved?

**Comment by cadecairos** [comment]
I'm gonna say yes
