### ISSUE TITLE
Design error states for desktop

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#34]

**Comment by cassiemc** [comment]
These are finished designs, I'll leave this open for a minute or two to answer any questions though.
* When there's an error, the field should highlight pink "#feeded" (<-- that is the actual hex code!)
* The outline of the field in question should turn dark pink #e7518f
* A 'warning' symbol appears at the far right of the field, also in dark pink #e7518f . We can use  fa-warning for that.
* a carrot and popup bubble appear with the actual error message, with the carrot aligned over the tip of the warning symbol
* on the signup designs, the ".makes.org" should turn from green to dark pink
* These warnings styles are the same as on the future mobile version, fyi

![error-login-desktop-v3](https://cloud.githubusercontent.com/assets/1186326/6794587/280579f6-d1aa-11e4-8fd6-7ae977270b1d.jpg)
![error-signup-desktop-v4](https://cloud.githubusercontent.com/assets/1186326/6794630/84292a2a-d1aa-11e4-87e3-97c73de849b0.jpg)

cc @alicoding

**Comment by alicoding** [comment]
I don't know how much we care about security here @cassiemc but being too specific about the error on the login is not a good practice here.

The error should always be an unknown to protect any hacking for example if I know the username exist I can keep guessing the password until I get it right, but if we say `Incorrect username or password.` that will make it harder to guess.

**Comment by jbuck** [comment]
Given that usernames are publicly viewable/searchable, I think giving a specific error to improve the UX is a net win

**Comment by alicoding** [comment]
@jbuck good point on that I guess I'm just used to see other sites like github or other ones where username also visible but they don't go specific on the error case... Another question then would be are we checking the username after they submit? From the UI I'm unclear if that was a check `onChange/onBlur` or only `onSubmit`.

**Comment by Pomax** [comment]
UX question about the fields: when a user selects an input field for typing in their username/password/email, the designs suggest the field's icon should disappear once there is content. Is that correct?

**Comment by cassiemc** [comment]
@alicoding re. specific field errors, not sure if there is a list somewhere but I was copying them straight from the ux in @thisandagain's omnigraffle files. I agree with @jbuck that it's an improved ux.

@Pomax – the only field that has an icon is the password field, and no need to hide that when the field is selected or there is an error state. It helps indicate what the field is for. If it's missing in my mocks, it's an oversight (my bad). The only thing that should happen when the user clicks into the field is that the field outline turns green and there is a cursor.

**Comment by cassiemc** [comment]
I will close this – designs for errors states are finished. See the second comment https://github.com/mozilla/id.webmaker.org/issues/34#issuecomment-85298635

You can download these images on dropbox here: https://www.dropbox.com/sh/z6b0a4lprkx2v1p/AADxObvDBmgfLxVRTh9XLGsOa?dl=0
