### ISSUE TITLE
Enable Single Page App login Flow

### ISSUE THREAD

**Issue by cadecairos** [mozilla/id.webmaker.org#356]
as per the details in:

http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified#browser-based-apps

we will add the option to pass response_type as "token" and for authorized client_ids, we'll return an api token in a url fragment to the callback url `https://example.org/singlepageapp#token=API_TOKEN` which should be the url of the single-page-app

cc/ @ashleygwilliams @jbuck

**Comment by jbuck** [comment]
I can dig it!

**Comment by cadecairos** [comment]
the code handling `/authorize` is pretty horrible...
