### ISSUE TITLE
No indication of successful password reset

### ISSUE THREAD

**Issue by vazquez** [mozilla/id.webmaker.org#361]
We need to show a visual indicator upon successful reset of the user's password.

**Message if user comes from Webmaker (or Teach, or any other app):** "Success! Your password has been reset. If you are not automatically sent back to Webmaker, [click here](#)."

**Message if user comes from id.webmaker.org:** "Success! Your password has been reset. Sign in with your new password below."

#### Designs

![1](https://cloud.githubusercontent.com/assets/1119821/9232893/30eb165c-40fe-11e5-8dd2-aab74aa954a3.png)  

![2](https://cloud.githubusercontent.com/assets/1119821/9232892/30e50050-40fe-11e5-93ea-6754f0c5ed5f.png)

**Comment by vazquez** [comment]
Resolving this issue helps in fixing mozilla/webmaker-core#441

**Comment by xmatthewx** [comment]
@cadecairos - ideally, we show the message then redirect users after about 3 seconds.

**Comment by cadecairos** [comment]
We're gonna need someone to do the HTML and CSS for these - adding the logic to redirect shouldn't be hard
Points of interest:
add message before redirection to android app here: https://github.com/mozilla/id.webmaker.org/blob/e89b16d4de94677b027c8521f250d5999f3b5df9/templates/pages/reset-password.jsx#L84-L101
add message for desktop based resets here: https://github.com/mozilla/id.webmaker.org/blob/e89b16d4de94677b027c8521f250d5999f3b5df9/templates/pages/login.jsx#L60

**Comment by cadecairos** [comment]
(I've got no idea how to make these look like the mockups)

**Comment by xmatthewx** [comment]
I believe @vazquez followed the style of existing notices in there. Regardless, these don't need to be fancy, just functional and not ugly.

**Comment by vazquez** [comment]
CSS is exactly the same, just the `fa` icons are changed, along with the
text.

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo
