### ISSUE TITLE
Design Webmaker welcome email - desktop

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#39]
Copy revisions being done in #42.

**Comment by cassiemc** [comment]
@secretrobotron is there content for this email?

**Comment by secretrobotron** [comment]
Let's go with what we've got for now, unless @HPaulJohnson has something different already. Right now, it's....

> Hi rw23r23r3w4,

> Welcome to Mozilla Webmaker! Thank you for joining us to explore, play and create together to build a web that's open and made by everyone.

> You can get started right now with these free tools:

> X-Ray Goggles allow you to see the code behind any webpage and remix elements with a single click, swapping in your own text and images.
> Thimble, an easy-to-use HTML and CSS editor, lets you learn code by writing it directly in your browser to create your own webpage.
> Popcorn Maker helps you combine content from across the web like GIFs, music, photos and videos into cool mashups that you can annotate and share.

> I'm so glad you've joined the Webmaker community. If you have questions, feel free to email me or tweet @webmaker. I'm looking forward to seeing what you make on the web!

> Cheers,
> Amira
> Webmaker Community Manager

> If you do not wish to receive any more emails from Mozilla Webmaker you can change your email preferences.



Note that
- Amira is the community manager
- Appmaker is missing
- It has no styling

**Comment by HPaulJohnson** [comment]
@secretrobotron How does this relate to https://github.com/MozillaFoundation/plan/issues/242?

Also just to clarify, this is the welcome for someone signing up for an account on webmaker.org? 

Copy needs updating regardless. Works fine for a placeholder for design but should be changed before it goes live. Happy to get that done if someone let's me know when it would be do by.

**Comment by cassiemc** [comment]
@HPaulJohnson We are going to hold on the design for this, but no reason to hold on copy updates. I've filed a new issue for that. We would probably need new copy by EOD Thurs to squeeze it into this heartbeat, does that sound right @secretrobotron? New issue is #42 (I couldn't seem to assign you, Paul)

**Comment by cassiemc** [comment]
I'm going to wiggle out from underneath this bug. @xmatthewx feel free to reassign, backlog or close at your will!

**Comment by xmatthewx** [comment]
Closing this. I think we have more critical tasks on our plate.
