### ISSUE TITLE
test-data script doesn't work with instructions given in thimble

### ISSUE THREAD

**Issue by errietta** [mozilla/id.webmaker.org#390]
From https://github.com/mozilla/thimble.webmaker.org/#installing-the-parts, in 1. Teach the ID server about the Publish server

It says to replace scripts/test-data.sql and then run node scripts/test-data.js

doing so errors:

psql:scripts/test-data.sql:6: ERROR:  invalid input syntax for type json
LINE 5:       'http://localhost:3500/callback' )
              ^
DETAIL:  Token "http" is invalid.
CONTEXT:  JSON data, line 1: http...

**Comment by humphd** [comment]
@sedge or @gideonthomas, do either of you have advice here?  This step seems to cause a lot of people to get stuck.

**Comment by sedge** [comment]
I've identified the problem: The id.wm.o database schema has changed since we published the instructions. The readme needs to be updated with this test script:

```sql
 INSERT INTO clients VALUES
    ( 'test',
      'test',
      '["password", "authorization_code"]'::jsonb,
      '["code", "token"]'::JSONB,
      'http://localhost:3500/callback' )
```

**Comment by errietta** [comment]
I r fix doc in pr

**Comment by sedge** [comment]
@errietta Can you confirm that the instructions work with the updated schema? If they do I'll give you an r+ in that patch.

**Comment by ashleygwilliams** [comment]
heads up i updated this in the `thimble` repo earlier https://github.com/mozilla/thimble.webmaker.org/commit/b7647eaee981790e4259b4d4f94b711e1dada19a

**Comment by ashleygwilliams** [comment]
so those should probably be aligned in some way

**Comment by sedge** [comment]
@ashleygwilliams I'm not sure I follow.

**Comment by sedge** [comment]
Yeah, this is a thimble issue. I'm going to close and file there
