### ISSUE TITLE
Send teach-specific welcome email when signed up through teach

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#4]
When users sign up through teach.mozilla.org (based on referral), they shouldn't receive the standard webmaker welcome email. Instead, they should receive a welcome email specific to teach.mozilla.org.

Need to
- [x] Craft welcome copy
- [x] Design email template - #35 (desktop) and #36 (mobile)
- [x] Implement email switching based on referral

@cassiemc @hannahkane @jbuck @Pomax anything you can see missing from ^^ list?

**Comment by hannahkane** [comment]
Welcome copy has been drafted here: https://teach.etherpad.mozilla.org/clubtransactionalemails

**Comment by secretrobotron** [comment]
:heavy_check_mark: thanks @hannahkane

**Comment by secretrobotron** [comment]
@hannahkane do you have plans to localize those transactional emails?

**Comment by hannahkane** [comment]
Eventually, but not in the immediate future.

**Comment by secretrobotron** [comment]
:+1: makes our lives easier this milestone

**Comment by cassiemc** [comment]
I have filed a separate design issue for this – https://github.com/mozilla/id.webmaker.org/issues/35

**Comment by secretrobotron** [comment]
@cadecairos what do we need to do (in sawmill?) in order to make this work?

**Comment by cadecairos** [comment]
we'll want to check for some specific teach related flag in https://github.com/mozilla/sawmill/blob/master/worker/send_new_user_email.js and change the email template we use in mailroom ( https://github.com/mozilla/webmaker-mailroom )

**Comment by cadecairos** [comment]
This is slightly blocked by #19 as once a new user is created through the id.wm.org/signup page, the id.wm.org user database code should trigger the [user_created worker](https://github.com/mozilla/sawmill/blob/0a4e685041f8eabb86dca685741aeb1214e2a4f8/worker/send_new_user_email.js) on sawmill to render the correct email template.

**Comment by secretrobotron** [comment]
@cadecairos #19 is closed now. This still blocked?

**Comment by secretrobotron** [comment]
Depends on #35.

**Comment by secretrobotron** [comment]
- Plaintext unless it's somehow easier to implement design in #43 (which I doubt)
- Copy below (from #35)
- Can replies to this email go to help@webmaker.org somehow? If not, we need to change some wording.

> Subject line: Welcome to the Mozilla Teach the Web Community!

> Welcome!

> Thanks for your interest in our global community of educators and activists who teach the web.

> We'll help you discover:

> · Free and open resources to teach your learners about the web - start with these [link to activities page]
> · Opportunities to become a better facilitative leader and mentor
> · Tips on using Webmaker tools to create and teach
> · Best practices from peers and future collaborators

> Start by putting your city on the map.

> If you're teaching the web in your local community, we want to know about it. Adding your club, program or classroom to our community map is simple, and allows us to send you locally relevant resources. If you don't have a local group yet, reply to this email to let us know you're interested, and we'll be in touch with you shortly.

> If you have any questions, we’re here to help. Our community loves to tweet and talk to new people – use the #teachtheweb hashtag to find us.

> Michelle Thorne
> on behalf of the Mozilla Learning team

**Comment by hannahkane** [comment]
Links implied in this copy:
 * "start with these" should link to teach.mozilla.org/activities/
 * "community map" should link to teach.mozilla.org/mozilla-web-clubs/

**Comment by hannahkane** [comment]
Also, I believe @amirad changed the email address we're using for support to teachtheweb@mozillafoundation.org, so replies should be directed to that email address, if possible.

**Comment by amirad** [comment]
That I did!

**Comment by secretrobotron** [comment]
@hannahkane verifying that clubs link should be  teach.mozilla.org/mozilla-web-clubs/ not /clubs, right?

**Comment by hannahkane** [comment]
Hmm...in https://github.com/mozilla/teach.webmaker.org/issues/618 we discussed changing the path to  /clubs, but it looks like that hasn't happened, so /mozilla-web-clubs/ is the right link.

If that changes in the future, I'll file another bug.

**Comment by secretrobotron** [comment]
:+1:

**Comment by secretrobotron** [comment]
Update: teachtheweb@mozillafoundation.org verified!
cc @jbuck @cadecairos
