### ISSUE TITLE
Update Webmaker Logo

### ISSUE THREAD

**Issue by vazquez** [mozilla/id.webmaker.org#405]
We need to update the Webmaker logo on all the id.webmaker.org properties 

![](https://cloud.githubusercontent.com/assets/1391451/10834130/9296d95c-7e9f-11e5-8f90-54331551e49a.jpg)

This relates to #294 #285

**Comment by cassiemc** [comment]
Thank you for filing this @vazquez this has been bugging me big time!

**Comment by ryanwarsaw** [comment]
This was landed in 602f3b7.
