### ISSUE TITLE
Unable to log into my webmaker account

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/id.webmaker.org#406]
Account: Ioana
Mail: chiorean.ioana@gmail.com

1. Opening the app today I got an empty profile- see attached screen. 
3. Logged out
3. Try to log in again
=> I was unable to log again, changed the password , not able to log in again

<img src="https://cloud.githubusercontent.com/assets/1391451/10935686/f7968482-82e7-11e5-8cc4-5d9ad0173a06.jpg" width="300" height="550" />

PS: 
* I did have projects made
* I tried with other account and worked ( testing account)

**Comment by xmatthewx** [comment]
We updated Webmaker Beta from 1.4 to 1.4.1 on Tuesday. Unfortunately, environment variables were set to use the staging server for user accounts. We'll get a patch up to fix this.  You'll can create a new account to use the app until it's switched to the real database.
