### ISSUE TITLE
Strangeness with login state

### ISSUE THREAD

**Issue by hannahkane** [mozilla/id.webmaker.org#416]
I went to webmaker.org/me to see if the re-direct would work, which it did. But when I landed on teach.mozilla.org/me, the page instructions were to sign in, even though I was already logged in, as you can see based on the "Hi hannahkane" in the top left.

![screen shot 2016-03-04 at 8 22 12 am](https://cloud.githubusercontent.com/assets/8389648/13533086/ad15d47a-e1e3-11e5-8892-a67a359d532b.png)

When I then logged out, I actually saw my projects.

![screen shot 2016-03-04 at 8 21 52 am](https://cloud.githubusercontent.com/assets/8389648/13533099/bd30f93e-e1e3-11e5-965f-ae17fde3888d.png)

**Comment by cadecairos** [comment]
I looked into this breifly, and have confirmed it's definitely a race condition between the teach-api component and the makepage component settings/accessing the username value.

**Comment by cadecairos** [comment]
@hannahkane I presume this is still an issue - should we still try to fix?

**Comment by hannahkane** [comment]
Yeah, I think we should. Would it be helpful if I come to a triage to see how it fits in compared to other items?

**Comment by cadecairos** [comment]
wont-fixing this due to inactivity
