### ISSUE TITLE
Login Issue with WebMaker

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [mozilla/id.webmaker.org#418]
I've tried to reset my password entering my email address 
![recover](https://cloud.githubusercontent.com/assets/5902032/14403859/ad2eb5e4-fe85-11e5-9097-3e7de91b2376.png)

and it says theres no account for that email address. however as below image it send email to my account.

![confirm](https://cloud.githubusercontent.com/assets/5902032/14403862/b81a87c6-fe85-11e5-8dbe-8bd0947b0ce9.png)

received this email 

![emailreover](https://cloud.githubusercontent.com/assets/5902032/14403874/fff1e9c2-fe85-11e5-9fdb-38ccf2d34146.png)
my user name field auto set as ruwan_ranganath , which include underscore , 
![nothinghappen](https://cloud.githubusercontent.com/assets/5902032/14403879/10f14ea2-fe86-11e5-9008-5cd9877cc528.png)

but the system not allow _ ( underscore ) in user name . 

![novalidusername](https://cloud.githubusercontent.com/assets/5902032/14403886/2e9e439c-fe86-11e5-8c77-2deda70cc193.png)

and later I received another password reset email which lead to this page : 
![password](https://cloud.githubusercontent.com/assets/5902032/14403903/9de13c28-fe86-11e5-98c8-98041bd6206d.png)

Password I used have both capital , simple letters , numbers , symbols so I assume it is not a issue with it . 

OS : Ubuntu 15.04 
Firefox version : 44

**Comment by cadecairos** [comment]
Thanks for including all those screenshots! I'll take a look at this as soon as I can.

**Comment by cadecairos** [comment]
@Ruwan-Ranganath Okay, I change your username to have a dash, instead of an underscore. give it a shot.

**Comment by cadecairos** [comment]
I want to clarify what's happening here: your account does exist, but not with the username you're trying to use. It was rowan_ranganath, and I've changed it to have a dash instead of an underscore. 

The second thing happening is that your account has never had a password set (we previously had a one-time password based system, but have since moved to user generated passwords.) When you enter your fixed username to sign in, it will tell you you don't have a password set. You will be able to request an email be sent to the email address associated with that username, and it will contain a link that will let you create a password for that account.

**Comment by Ruwan-Ranganath** [comment]
Thank you @cadecairos :+1: 
password resetting is successful . 
but when i use my logins at : https://id.webmaker.org/login/ 
it redirect to the page with this message : 

> {"statusCode":400,"error":"Bad Request","message":"child \"client_id\" fails because [\"client_id\" is not allowed to be empty]","validation":{"source":"query","keys":["client_id"]}}

![id webmaker](https://cloud.githubusercontent.com/assets/5902032/14404156/4b4bcc88-fe8d-11e5-9a12-cf905876c5b5.png)

**Comment by cadecairos** [comment]
That's a known problem, it's because the login pages aren't meant to be used directly, but as an OAth provider for other services. Try logging in with thimble: https://thimble.mozilla.org

**Comment by Ruwan-Ranganath** [comment]
I just tried on my mobile phone and it works perfect . 

device : OnePlus One 
OS : Android 6.01 Cynogen 13.0

**Comment by Ruwan-Ranganath** [comment]
Works fine ! 
@cadecairos  thank you :)

**Comment by nailaandleeb** [comment]
not working with thimble too.

    {statusCode: 400,error: "Bad Request",message: "child "client_id" fails because ["client_id" is not allowed  be empty]",validation: - {source: "query",keys: - ["client_id"]}}

m deploying it locally on my system.
