### ISSUE TITLE
Design teach-specific welcome email when signed up through teach - desktop

### ISSUE THREAD

**Issue by cassiemc** [mozilla/id.webmaker.org#43]
Copy is in #35

**Comment by cassiemc** [comment]
I have a first draft. We might want to make some adjustments to rearrange elements or simplify content? Feedback @hannahkane and @vazquez? Redpen is here: https://redpen.io/hj568a8785c8ccb836

![teach-welcome-email](https://cloud.githubusercontent.com/assets/1186326/6877389/09ab59e4-d4a7-11e4-9826-0682c3638859.jpg)

**Comment by cassiemc** [comment]
Oh yes and we should make sure using that picture of Michelle is okay with @thornet :)

**Comment by hannahkane** [comment]
<3. Looks great!

**Comment by cassiemc** [comment]
Ok cool. Will upload assets and close.

**Comment by cassiemc** [comment]
All assets including the .psd are here: https://www.dropbox.com/sh/6bivzh6jj9mhq3i/AABDz0q2flIXUZ1u4GOs18WGa?dl=0

Note for @hannahkane – we may want @vazquez to update the header image in this email if the images change on the teach site.

Here's the final design:
![teach-welcome-email-approved](https://cloud.githubusercontent.com/assets/1186326/6926525/d10ad5cc-d7b4-11e4-96ae-50b3f4b35728.jpg)

Closing this!

**Comment by vazquez** [comment]
cc @sabrinang on the possible image change

**Comment by cassiemc** [comment]
My bad! Thanks @vazquez @sabrinang
