### ISSUE TITLE
create a passport wrapper

### ISSUE THREAD

**Issue by Pomax** [mozilla/id.webmaker.org#431]
Based on https://github.com/jaredhanson/passport-oauth2 we should write a passport wrapper so that thimble can make use of that, in preparation for using "any other thing that has a passport wrapper available".

**Comment by ryanwarsaw** [comment]
I'm going to temporarily un-assign myself in-case someone wants to take this, I really don't have as much time as I thought I was going to in order to not only implement this, but also complete the work involved in making it possible to use 3rd party services (see the ticket above).

**Comment by Pomax** [comment]
Is there a branch on your repo that we can link to to act as basis for further work by others? (or perhaps even specific files?)
