### ISSUE TITLE
Add linting/mofo-style

### ISSUE THREAD

**Issue by k88hudson** [mozilla/id.webmaker.org#47]
Before it gets too big!

**Comment by k88hudson** [comment]
@gvn want to help with this one?

**Comment by gvn** [comment]
Sure, what's the task runner?

**Comment by k88hudson** [comment]
npm scripts

**Comment by gvn** [comment]
Gulp makes more sense to me for linting.

**Comment by alicoding** [comment]
Can't we simply do something like:

```
"scripts": {
    "lint": "jshint **.js",
    ...
    ...
```

That's just for jshint with simple path. I'm just suggesting and open to suggestion as to why Gulp would be better for linting.

**Comment by gvn** [comment]
Yep, we *can* do that and I'm going to actually try the npm scripts approach. I just can't help but feel we're re-inventing some wheels here (especially once we get more fancy...globbing, multi-tasks, chains, etc), but I'll see how it feels.

**Comment by gvn** [comment]
Dupe of #57 

:sob:

**Comment by k88hudson** [comment]
Arhhhhhh I'm sorry!

**Comment by k88hudson** [comment]
Yay for it being done though

**Comment by gvn** [comment]
No worries...it was a learning experience.

![retreat](https://cloud.githubusercontent.com/assets/206379/6813430/5dcaa6f0-d232-11e4-86f7-4afc2387261e.gif)
