### ISSUE TITLE
change node_modules/autoless/... to autoless (in package.json)

### ISSUE THREAD

**Issue by k88hudson** [mozilla/id.webmaker.org#48]
`node_modules/autoless/bin/autoless` can be shortened to `autoless` since executables in npm dependencies get automatically added to the PATH for npm scripts

See http://blog.ibangspacebar.com/npm-scripts/

**Comment by alicoding** [comment]
@k88hudson if tested on Windows and working without the specified path then lets change that. We did that yesterday because of Cross Platform Compatibility issue only otherwise I don't see a point of that :)

**Comment by k88hudson** [comment]
it's actually better for windows since npm handles the path/directory issues for you this way :)

**Comment by jbuck** [comment]
This has been fixed
