### ISSUE TITLE
Implement user migration page

### ISSUE THREAD

**Issue by alicoding** [mozilla/id.webmaker.org#53]
See #28 for designs.

cc @secretrobotron @cassiemc

**Comment by Pomax** [comment]
Final screens from the above ticket:

![01-enter-username](https://cloud.githubusercontent.com/assets/1186326/6829903/d73d2c78-d2ec-11e4-8e7e-01f6c60d77d5.jpg)
![02-enter-token](https://cloud.githubusercontent.com/assets/1186326/6829904/d73f3e96-d2ec-11e4-9521-2cf3f6815e72.jpg)
![03-set-password](https://cloud.githubusercontent.com/assets/1186326/6829905/d7415a78-d2ec-11e4-85b3-770aed1cd902.jpg)
![04-success-v2](https://cloud.githubusercontent.com/assets/1186326/6829906/d74173e6-d2ec-11e4-9e02-a6ad462cdcf0.jpg)

**Comment by secretrobotron** [comment]
@cadecairos is working on a good flow for this at the moment, which will let users click on a link in an email to hop right to the password reset screen.

**Comment by secretrobotron** [comment]
@alicoding @cadecairos can this close now?

**Comment by alicoding** [comment]
I think so. Right now I'm only working on the UX for many different cases but that we already filed them in different tickets.
