### ISSUE TITLE
Implement sign-in page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#6]
- [x] page stub
- [x] client-side username/password validation/acceptance
  - [x] usernames: at least 1 character
  - [x] password at least 8 characters
- [x] server-side username/password acceptance (?)
- [x] expose a URI for this page

**Comment by alicoding** [comment]
Are we waiting for the design of this page too? Or we already have them ready?

**Comment by secretrobotron** [comment]
@alicoding: @cassiemc's design should work: https://github.com/mozilla/webmaker.org/issues/1366#issuecomment-82416705

**Comment by alicoding** [comment]
If a user prompt to sign-in but they don't have an account. Should we redirect them to another page to signup for an account or just switch the UI to account creation in the same page?

CC: @cassiemc @secretrobotron

**Comment by secretrobotron** [comment]
They should see the account creation page *somehow*. Your question sounds like a technical one though. Depending on the framework, it might be easiest to just do a redirect.

**Comment by Pomax** [comment]
added some checkboxes to the top comment to track what needs to be done

**Comment by Pomax** [comment]
We can probably use https://www.npmjs.com/package/client-oauth2 to take care of the "all fields check out, let's log in using oauth2" part

**Comment by alicoding** [comment]
@cassiemc I used this one for sign-in

![https://cloud.githubusercontent.com/assets/1186326/6761141/51beb298-cf26-11e4-88b2-45ac3dcaf54a.jpg]()

**Comment by alicoding** [comment]
This is what I implemented:

![screen shot 2015-03-23 at 17 12 35](https://cloud.githubusercontent.com/assets/4368149/6790699/e60cdf50-d17f-11e4-8530-79fd524c2e03.png)

**Comment by alicoding** [comment]
TODO: 

- [ ] Update Logo to match the design
- [ ] Hide font-awesome icon on focus
- [ ] Display warning onBlur and display another font-awesome
- [ ] Hook this up with the API route
- [ ] Design QA (push this up somewhere maybe?)

**Comment by alicoding** [comment]
cc @secretrobotron @Pomax things to do listed above FYI

**Comment by alicoding** [comment]
Latest design ![](https://cloud.githubusercontent.com/assets/1186326/6794410/c75731a0-d1a7-11e4-8dd6-943127dce650.jpg)

**Comment by alicoding** [comment]
https://www.dropbox.com/sh/vkyp3r1051wbd9j/AAAOhsm2t1QJ6GlwhazE551Pa?dl=0

**Comment by Pomax** [comment]
There is an additional requirement here, where the question mark in the designs should lead the user to the password reset page.

**Comment by cassiemc** [comment]
@pomax ixnay on the question mark. I have reopened #27 and am going to add a 'need help' link in lieu of the question mark.

**Comment by Pomax** [comment]
duly ixnayed.

**Comment by Pomax** [comment]
it does look like the new design has the wordmark next to the logo for the login page, so that simplified `Header` a little @alicoding

**Comment by alicoding** [comment]
1. If the user filled in their username and click log in without filling the password field. We will (A) redirect them to user migration page if they don't have password before or (B) if they have password before and didn't put the password we will give them an error.

2. If the user filled in the username and click "Need help?" link and (A) they never set a password before we will redirect them to user migration page or (B) we will redirect them to password reset page

3. If the user didn't filled any of the field and click on "Need help" we will always redirect them to password reset page
This last one we can also detect in the password reset page if they actually need password reset or user migration

**Comment by alicoding** [comment]
All the UI for this page is completed and I think the API is plugged too, maybe? @cadecairos ?

**Comment by jbuck** [comment]
Yeah, this is done
