### ISSUE TITLE
document how to make the client contact the server

### ISSUE THREAD

**Issue by Pomax** [mozilla/id.webmaker.org#67]
Looking at https://www.npmjs.com/package/client-oauth2 and the lack of docs on our side, it will be important to know what values should go into a client-side oauth2 manager in order to be able to start negotiating access, as well as which grant types we're using so that for client-oauth2, specifically, we can document which code calls need to be used in order to effect a login.

I tried slotting client-oauth2 into the signup.jsx data handler, once a user has filled in data that passes client-side validation, but it's not clear what needs to happen to make this work.

Even a quick and terse "you just cloned login.wmo and id.wmo, now do this: 1) ... 2) ... 3) ... 4) require client-oauth2, build with options: ..., 5) call client.credentials.something(), 6)... " will be invaluable while we sprint on this.

**Comment by secretrobotron** [comment]
@cadecairos @jbuck mind ironing this out before @Pomax gets back to work tomorrow?

**Comment by jbuck** [comment]
So, we simplified it down to moving the login-related bits out of the existing `POST /login/oauth/authorize` route into a `POST /login` route and only having the `POST /login/oauth/authorize` route check for a signed-in state. @cadecairos is doing this in #74. So the id.wm.o front-end only needs to do an XHR `POST /login` to sign-in.

**Comment by secretrobotron** [comment]
Woooot! cc @Pomax

**Comment by Pomax** [comment]
process question there if login state requires the user to log in: clients post POST to /login, if the user is already cookied up correctly the client-registered-callback immediately gets called, otherwise the login page that was made as part of the front-end work is presented to the user to fill in a username/password?
