### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by k88hudson** [mozilla/id.webmaker.org#69]
I talked to a couple of people at npm, seems like they're using/trying out http://www.appveyor.com/ to do windows CI. Takes some configuring, but apparently works.

I think it would be worth giving it a try (at some point)

**Comment by k88hudson** [comment]
cc @simonwex, since we were talking/you wanted to know

**Comment by ryanwarsaw** [comment]
This was done in 4a04ba18d0568369cad05091a494e02b9323855a
