### ISSUE TITLE
Implement password reset page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#7]

**Comment by cassiemc** [comment]
Here are the final designs from #30.

They can be downloaded here: https://www.dropbox.com/sh/ttu7vkoq9irawp1/AABg9lTGDBkSYzj_hdW7RZ3Aa?dl=0

Icons are font-awesome, but if you need svgs they are here:
https://www.dropbox.com/sh/vkyp3r1051wbd9j/AAAOhsm2t1QJ6GlwhazE551Pa?dl=0

![01-username](https://cloud.githubusercontent.com/assets/1186326/6836549/68b5e402-d319-11e4-8036-8058e0ba5125.jpg)
![02-notifcation](https://cloud.githubusercontent.com/assets/1186326/6836548/68b5b1bc-d319-11e4-89d5-8d64fb70e245.jpg)
![03-reset-email](https://cloud.githubusercontent.com/assets/1186326/6836547/68b4379c-d319-11e4-98ab-278f30c0ab85.jpg)
![04-new-password](https://cloud.githubusercontent.com/assets/1186326/6836550/68b6c84a-d319-11e4-8604-e5abd30c0739.jpg)

**Comment by cassiemc** [comment]
One update, as @alicoding and I discussed in IRC this morning, is that the initial button will be "Set new password" instead of "reset password" in order to make sure all user scenarios are covered.

**Comment by alicoding** [comment]
The UI for this page is completed and only need to plug in the API.

**Comment by secretrobotron** [comment]
@cadecairos this is hooked up now?

**Comment by cadecairos** [comment]
yes!
