### ISSUE TITLE
Implement sign up / account creation page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/id.webmaker.org#8]
- [x] stub page
- [x] style page
- [x] hook up to the user registration system

**Comment by alicoding** [comment]
Sign-up redpen here: https://redpen.io/br89c5f885f87fd81c

cc @Pomax @cassiemc

**Comment by alicoding** [comment]
[https://cloud.githubusercontent.com/assets/1186326/6790428/e10d7c0a-d17d-11e4-9f99-90418a634fbc.jpg](https://cloud.githubusercontent.com/assets/1186326/6790428/e10d7c0a-d17d-11e4-9f99-90418a634fbc.jpg)

**Comment by Pomax** [comment]
@cassiemc Is that background available as dedicated graphic anywhere?

**Comment by alicoding** [comment]
@Pomax is this the one https://github.com/mozilla/webmaker.org/blob/master/public/img/home/background.jpg

**Comment by Pomax** [comment]
perfect, thank you

**Comment by alicoding** [comment]
The UI for this page is completed I think only the API left to be plug in.

**Comment by secretrobotron** [comment]
@cadecairos this is hooked up now?

**Comment by cadecairos** [comment]
Yes, I think so.
