### ISSUE TITLE
npm test fails on windows during jshint stage

### ISSUE THREAD

**Issue by toolness** [mozilla/id.webmaker.org#98]
Here is where it explodes:

```
> id.webmaker.org@1.0.0 lint c:\Users\Atul\Documents\mozilla\id.webmaker.org
> npm run jshint && npm run jscs


> id.webmaker.org@1.0.0 jshint c:\Users\Atul\Documents\mozilla\id.webmaker.org
> jshint lib test web *.js

ERROR: Can't open *.js
ERROR: Can't parse config file: c:\Users\Atul\Documents\mozilla\id.webmaker.org\.jshintrc
Error:SyntaxError: Unexpected token o
```

I'm using Windows 7 and this seems to happen with both `cmd.exe` and the `bash` that comes with Git for Windows.

**Comment by toolness** [comment]
So as @Pomax pointed out on IRC, it seems the second error is due to the fact that `.jshintrc` is a symlink, which breaks on Windows. I recommend we do what the Teach site does and [point jshint directly at the real .jshintrc in node_modules](https://github.com/mozilla/teach.webmaker.org/blob/develop/gulpfile.js#L174-L178).

**Comment by toolness** [comment]
I suspect that the `Can't open *.js` might be happening with `cmd.exe` on Windows because that glob is expanded to actual filenames by a Unix-style shell, but [not by `cmd.exe`](http://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths). However, I'm surprised such a thing also doesn't work when running `bash` on my Windows system.

**Comment by Pomax** [comment]
I think cygwin bash does a callthrough to window's file system management, so paths generally work, but symlinks/junctions run into problems.

**Comment by jbuck** [comment]
On windows `*.js` will be passed through directly instead of being expanded by bash, but this generally isn't a problem for node apps that use glob or minimatch since those will do the expansion. I think.

**Comment by Pomax** [comment]
yeah ddefinitely for jslint, glob *should* be taking care of that
